// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migraties draaien bij voorkeur over een directe (niet-gepoolde) verbinding.
    // Vercel's Neon-integratie gebruikt een `wisdom_`-prefix; lokaal de kale naam.
    url:
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["wisdom_DATABASE_URL_UNPOOLED"] ??
      process.env["DATABASE_URL"] ??
      process.env["wisdom_DATABASE_URL"],
  },
});
